#ifndef EI_CLASSIFIER_CONFIG_H
#define EI_CLASSIFIER_CONFIG_H

// Force disable CMSIS-NN
#define EI_CLASSIFIER_TFLITE_ENABLE_CMSIS_NN 0
#define EI_CLASSIFIER_TFLITE_LOAD_CMSIS_NN_SOURCES 0
#define EIDSP_LOAD_CMSIS_DSP_SOURCES 0

// Additional configuration
#define EI_CLASSIFIER_TFLITE_ENABLE_ESP_NN 1
#define EI_CLASSIFIER_TFLITE_ENABLE_ESPRESSIF 1

#endif // EI_CLASSIFIER_CONFIG_H